# Use an official Node.js runtime as a parent image
FROM node:20.11.1

# Set the working directory
WORKDIR /app

ARG DATABASE_URL
ARG DIRECT_URL
ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG FRONTEND_URL
ARG GOOGLE_CLOUD_PROJECT_ID
ARG GOOGLE_CLOUD_API_KEY
ARG OPENAI_API_KEY
ARG DEEPGRAM_API_KEY
ARG GCS_BUCKET_NAME
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG GOOGLE_STORAGE_EMAIL
ARG GOOGLE_STORAGE_PRIVATE_KEY

RUN echo $DATABASE_URL
RUN echo $DIRECT_URL
RUN echo $SUPABASE_URL
RUN echo $SUPABASE_ANON_KEY
RUN echo $SUPABASE_SERVICE_ROLE_KEY
RUN echo $FRONTEND_URL
RUN echo $GOOGLE_CLOUD_PROJECT_ID
RUN echo $GOOGLE_CLOUD_API_KEY
RUN echo $OPENAI_API_KEY
RUN echo $DEEPGRAM_API_KEY
RUN echo $GCS_BUCKET_NAME
RUN echo $GOOGLE_APPLICATION_CREDENTIALS
RUN echo $GOOGLE_STORAGE_EMAIL
RUN echo $GOOGLE_STORAGE_PRIVATE_KEY

# Copy package.json and package-lock.json
COPY package*.json ./

# Install pnpm globally
RUN npm install -g pnpm

# Install project dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN pnpm run build-backend

# Expose the port the app runs on
EXPOSE 8080

# Start the application
CMD ["pnpm", "start-backend"]