import "@/styles/globals.css";
import "react-toastify/dist/ReactToastify.css"; // Add this line

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

import { Nunito_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={nunitoSans.className}>
        <TRPCReactProvider>
          {children}
          <ToastContainer />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
